DROP TABLE IF EXISTS PLAYERS;
CREATE TABLE PLAYERS (ID INTEGER PRIMARY KEY, NAME VARCHAR NOT NULL, BIRTH_DATE TIMESTAMP);

INSERT INTO PLAYERS VALUES(1001, 'Fury Tycoon', '2001-03-04');
INSERT INTO PLAYERS VALUES(1002, 'Mike Tyson', '1999-10-03');