DROP TABLE IF EXISTS DEAL;
CREATE TABLE DEAL (ID VARCHAR PRIMARY KEY, TITLE VARCHAR , DESCRIPTION VARCHAR, DEAL_PRICE_AMOUNT DOUBLE, NORMAL_PRICE_AMOUNT DOUBLE, REDEEMABLE_FROM DATE, REDEEMABLE_TO DATE, VERSION INTEGER);

INSERT INTO DEAL VALUES ('LEVIS_501', 'Levis 501', 'Traditional Jeans', 33.00, 70.00, PARSEDATETIME('24.12.2016', 'dd.MM.yyyy'), CURRENT_DATE(), 0);