CREATE SCHEMA IF NOT EXISTS myschema 
       AUTHORIZATION "D022051";

DROP TABLE IF EXISTS DEAL;

CREATE TABLE DEAL
(
   ID                    VARCHAR PRIMARY KEY,
   TITLE                 VARCHAR,
   DESCRIPTION           VARCHAR,
   DEAL_PRICE_AMOUNT     DOUBLE PRECISION,
   NORMAL_PRICE_AMOUNT   DOUBLE PRECISION,
   REDEEMABLE_FROM       DATE,
   REDEEMABLE_TO         DATE,
   VERSION               INTEGER
);