DROP TABLE IF EXISTS DEAL;
CREATE TABLE DEAL (ID VARCHAR PRIMARY KEY, TITLE VARCHAR , DESCRIPTION VARCHAR, DEAL_PRICE_AMOUNT DOUBLE, NORMAL_PRICE_AMOUNT DOUBLE, REDEEMABLE_FROM DATE, REDEEMABLE_TO DATE, VERSION INTEGER);
